[package]
name = "hops"
version = "0.1.0"
authors = ["J. Cliff Dyer <jcd@sdf.org>"]

[dependencies]
bytes = "*"
clap = "*"
futures = "*"
rand = "*"
serde = "*"
serde_derive = "*"
serde_json = "*"
tokio = "0.1"
tokio-io = "0.1"
